[package]
name = "krachlicht"
version = "0.1.0"
authors = ["Marcel Kummer"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dft = "0.5.*"
sdl2 = "0.34.5"
