pa_device = "invalid"
osc_listen_addr = "0.0.0.0:8000"
osc_dst_addr = "127.0.0.1:9000"
ola_host_addr = "127.0.0.1:7770"
mqtt_broker_url = "tcp://hostname:1883"
mqtt_discovery_prefix = "homeassistant"
mqtt_unique_id = "krachlicht"
